---
- hosts: all
  #become: yes
  gather_facts: yes
  vars:
  - container_prefix: "test-container-"
  - lxc_templates:
    - ubuntu
    - debian
    - alpine
    - centos
    #- fedora
  # Install Docker
  roles:
    - role: angstwad.docker_ubuntu
      become: yes
      # Workaround bionic no docker-ce stable could be delete
      apt_repository: "deb [arch={{ apt_repository_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} artful {{ docker_apt_channel }}"
      docker_group_members:
        - "{{ansible_user_id}}"
      tags:
        - docker

  tasks:
    - block:
      - name: "Install lxc-dev needed packages"
        become: yes
        apt:
          name: "{{ item }}"
          state: present
          update_cache: yes
          cache_valid_time: 3600
        with_items:
          - lxc
          - lxc-templates
          - python-lxc
          - openvswitch-switch
          - lvm2
          - btrfs-tools
          - zfsutils-linux
          - libvirt-bin
          - libvirt-dev
          - python-libvirt
          - python3-libvirt
          - virtinst
          # Not in bionic
          #- cgmanager
          - cgroup-lite
          - debootstrap
          - bridge-utils
          - yum
          - rpm
          # - zypper
          - qemu-user-static
          #- haproxy
          - open-iscsi
          #- redis-server
          #- rabbitmq-server
          - dnsmasq

      #- name: "Extend ubuntu template"
      #  become: yes
      #  replace:
      #      regexp: "apt-transport-https,ssh,vim"
      #      # The regular expression to look for in the contents of the file.
      #      # Uses Python regular expressions;
      #      # see U(http://docs.python.org/2/library/re.html).
      #      # Uses multiline mode, which means C(^) and C($) match the beginning
      #      # and end respectively of I(each line) of the file.
      #      dest: "/usr/share/lxc/templates/lxc-ubuntu"
      #      # The file to modify.
      #      replace: "apt-transport-https,ssh,vim,manpages,man-db,bash-completion,whois,acl,python,python-apt,dnsutils,nmap,nginx,mongodb,python-flask,python3-flask"
      #  ignore_errors: yes

      #- name: Create a stopped container
      #  become: yes
      #  lxc_container:
      #    name: "{{container_prefix}}{{item}}"
      #    container_log: true
      #    template: "{{item}}"
      #    state: stopped
      #  with_items: "{{lxc_templates}}"
      #  #ignore_errors: yes

      #- name: Remove container
      #  become: yes
      #  lxc_container:
      #    name: "{{container_prefix}}{{item}}"
      #    container_log: true
      #    template: "{{item}}"
      #    state: absent
      #  with_items: "{{lxc_templates}}"
        #ignore_errors: yes
      tags:
        - lxc-dev
